### ISSUE TITLE
Fix spacing between vision and console components to match the design

### ISSUE THREAD

**Issue by Akalanka47000** [sliit-foss/timekeeper-web#30]
![image](https://github.com/sliit-foss/timekeeper-web/assets/73662613/9f479852-b032-433b-857d-38ddcad0c51e)

**Comment by AdamRathbun** [comment]
Hi Akalanka47000, this is my first time doing open source—I'd love to contribute. Are you looking to increase the spacing between these? The spacing already looks similar to your image. Please let me know how I can help!

**Comment by Akalanka47000** [comment]
Hi Adam, thanks for reaching out. The spacing needs to decrease to match the Figma design, you can find the link to it in the [README](https://github.com/sliit-foss/timekeeper-web/blob/main/README.md#figma) file
