### ISSUE TITLE
Link footer socials to actual pages

### ISSUE THREAD

**Issue by Akalanka47000** [sliit-foss/timekeeper-web#32]

**Comment by anubhav1206** [comment]
Where are the links to socials? I can work on this

**Comment by Akalanka47000** [comment]
> Where are the links to socials? I can work on this

Hello, there's already an assignee for this issue, shall we leave it out for a while ?

**Comment by Utkarshrajmishra** [comment]
Hey, @Akalanka47000 is this issue still open? If yes, can you please assign it to me?

**Comment by Akalanka47000** [comment]
> Hey, @Akalanka47000 is this issue still open? If yes, can you please assign it to me?

@probablyshabina any update on the linked PR? If not we can assign this to @Utkarshrajmishra

**Comment by probablyshabina** [comment]
I’ll make the requested changes and close the issue asap.
