### ISSUE TITLE
Fix documentation horizontal alignment to match header

### ISSUE THREAD

**Issue by Akalanka47000** [sliit-foss/timekeeper-web#59]
![image](https://github.com/sliit-foss/timekeeper-web/assets/73662613/b6775a69-ffdd-45a6-8024-5f8526b73898)

**Comment by Utkarshrajmishra** [comment]
Hey, @Akalanka47000  can you please assign me this issue?

**Comment by Utkarshrajmishra** [comment]
Hey, @Akalanka47000 can you please assign this issue to me?

**Comment by Akalanka47000** [comment]
> Hey, @Akalanka47000 can you please assign this issue to me?

My pleasure

**Comment by Akalanka47000** [comment]
Closing this issue since there has been a slight change in animations which invalidates this. This commit fixes a similar context.

Thank you very much for the support @Utkarshrajmishra. Apologies if any inconvenience is being caused.
