### ISSUE TITLE
Remove border around logo on focus

### ISSUE THREAD

**Issue by Akalanka47000** [sliit-foss/timekeeper-web#62]
![image](https://github.com/sliit-foss/timekeeper-web/assets/73662613/505eb8f6-bbbd-4c63-aa61-44709e0d40cc)

![image](https://github.com/sliit-foss/timekeeper-web/assets/73662613/64fa16b8-f704-42fd-93b3-0a8e251d7d75)

![image](https://github.com/sliit-foss/timekeeper-web/assets/73662613/999896e9-8c9e-40f8-81c1-b2e5020d65de)

**Comment by sohaibaumer** [comment]
can i get assigned?

**Comment by Akalanka47000** [comment]
> can i get assigned?

Sure, lemme go ahead and assign it
