### ISSUE TITLE
Clock logo in footer of docs page is messed up

### ISSUE THREAD

**Issue by Dhruv-Sood** [sliit-foss/timekeeper-web#68]
<img src="https://ibb.co/rbp11TY"><img src="https://i.ibb.co/3fFLLG2/Screenshot-2023-07-13-at-12-03-36-AM.png" alt="Screenshot-2023-07-13-at-12-03-36-AM" border="0"></img>

**Comment by Akalanka47000** [comment]
Looks like this is specific to safari, let me check
