### ISSUE TITLE
Remove button highlight on long press (mobile)

### ISSUE THREAD

**Issue by Akalanka47000** [sliit-foss/timekeeper-web#75]
![image](https://github.com/sliit-foss/timekeeper-web/assets/73662613/cbc621c2-c0a3-4aac-8eb8-355b41a558fb)

**Comment by avinashji1302** [comment]
> 
 you mean  background color of "Get started button"  ?

**Comment by Akalanka47000** [comment]
> > 
> 
> you mean background color of "Get started button" ?

No, the blue color highlight once you press and hold on the buttons.
