### ISSUE TITLE
[Firefox] - animated borders missing around cards

### ISSUE THREAD

**Issue by Akalanka47000** [sliit-foss/timekeeper-web#80]
Expected - 

![image](https://github.com/sliit-foss/timekeeper-web/assets/73662613/a2234039-b7b2-44c1-9ced-a27fc053ded5)

Actual - 

![image](https://github.com/sliit-foss/timekeeper-web/assets/73662613/5b50981e-ff07-4a15-b024-42320ac27041)

**Comment by Kashif-Saleem-Ghuman** [comment]
@Akalanka47000 I don't see any contributing guidelines. So I am assuming I shall just fix the issue and open a PR, right?

**Comment by Akalanka47000** [comment]
> @Akalanka47000 I don't see any contributing guidelines. So I am assuming I shall just fix the issue and open a PR, right?

Hi, @Kashif-Saleem-Ghuman, we're yet to lay them out, for now it's a yes for your question. I'll make sure to set up the guidelines within the coming day or the next.

**Comment by Kashif-Saleem-Ghuman** [comment]
ok @Akalanka47000 So I am working on this issue
But on the figma I don't see the above page
Here is a screenshot of the FIgma I see 
![image](https://github.com/sliit-foss/timekeeper-web/assets/111677605/4d28101e-103b-4288-bb0c-3923ba04802d)

**Comment by Akalanka47000** [comment]
> ok @Akalanka47000 So I am working on this issue But on the figma I don't see the above page Here is a screenshot of the FIgma I see ![image](https://user-images.githubusercontent.com/111677605/253923639-4d28101e-103b-4288-bb0c-3923ba04802d.png)

Unfortunately, there isn't a separate design created for this page. It was created on whim. The exact design which needs to be matched is available if you visit this on a chromium browser. Firefox however has a few problems which are the ones which needs to be fixed. This issue targets one of them.

**Comment by Kashif-Saleem-Ghuman** [comment]
@Akalanka47000 okay

**Comment by Akalanka47000** [comment]
> @Akalanka47000 okay

I'm assigning you to the issue then, let me know if you come across any problems

**Comment by Kashif-Saleem-Ghuman** [comment]
@Akalanka47000  Yes I ran in both browsers, on Chrome the animated borders show up, but on Firefox, they don't. So I am working on it now.
