### ISSUE TITLE
[Firefox] - Fix scrollbar color and width

### ISSUE THREAD

**Issue by Akalanka47000** [sliit-foss/timekeeper-web#82]
Expected - 

![image](https://github.com/sliit-foss/timekeeper-web/assets/73662613/8e25379e-5901-4d78-88da-0aea96cc8879)

Actual - 

![image](https://github.com/sliit-foss/timekeeper-web/assets/73662613/945ccd33-f5f9-41df-9f70-870c61fa1635)

**Comment by CaglayanCaliskan** [comment]
https://github.com/sliit-foss/timekeeper-web/pull/83
