### ISSUE TITLE
Resize favicon to a 1:1 aspect ratio

### ISSUE THREAD

**Issue by Akalanka47000** [sliit-foss/timekeeper-web#85]
As of now since the dimensions aren't one to one the icon is displayed as follows. The following screenshot is in firefox but the scenario might apply to multiple other places

![image](https://github.com/sliit-foss/timekeeper-web/assets/73662613/b697c485-05ea-4fa5-b0b7-da216d1be240)

**Comment by NishantEC** [comment]
hey @Akalanka47000 i'd like to work on the issue, please assign me.

**Comment by Akalanka47000** [comment]
> hey @Akalanka47000 i'd like to work on the issue, please assign me.

Hey @NishantEC, sure
